version: '3'
services:
  app:
    build: ./app
    restart: always
    volumes:
      - type: bind
        source: ./volumes/app
        target: /var/www/html
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./volumes/app
        target: /var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./volumes/mysql
        target: /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1