version: '3'
services:
  app:
    image: php:7.1.11-fpm-alpine
    volumes:
      - './volumes/app:/var/www/html'
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './volumes/app:/var/www/html'
      -  './volumes/nginx:/etc/nginx/conf.d'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./volumes/mysql
        target: /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1